//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;
using System.Resources;

[assembly: AssemblyTitle("PERLS.iOS")]
[assembly: AssemblyDescription("PERLS-v2")]
[assembly: AssemblyCompany("ADL")]
[assembly: AssemblyProduct("PERLS.iOS")]
[assembly: AssemblyVersion("3.0.0.0")]
[assembly: AssemblyFileVersion("3.0.0.0")]
[assembly: AssemblyInformationalVersion("3.0.0+Branch.tags-3.0.0.Sha.9c58b2fc004e4a77ea0b28d5d468e794493a0e79")]
[assembly: AssemblyCopyright("ADL")]
[assembly: AssemblyConfiguration("Release")]
[assembly: ComVisible(false)]

// Custom Attributes
[assembly: NeutralResourcesLanguage("en")]
