//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PERLS.Data {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PERLS.Data.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string DoneLabel {
            get {
                return ResourceManager.GetString("DoneLabel", resourceCulture);
            }
        }
        
        public static string CloseLabel {
            get {
                return ResourceManager.GetString("CloseLabel", resourceCulture);
            }
        }
        
        public static string NewEmptyMessage {
            get {
                return ResourceManager.GetString("NewEmptyMessage", resourceCulture);
            }
        }
        
        public static string TrendingEmptyMessage {
            get {
                return ResourceManager.GetString("TrendingEmptyMessage", resourceCulture);
            }
        }
        
        public static string RecommendationsEmptyTitle {
            get {
                return ResourceManager.GetString("RecommendationsEmptyTitle", resourceCulture);
            }
        }
        
        public static string RecommendationsEmptyMessage {
            get {
                return ResourceManager.GetString("RecommendationsEmptyMessage", resourceCulture);
            }
        }
        
        public static string EmptyPodcastTitle {
            get {
                return ResourceManager.GetString("EmptyPodcastTitle", resourceCulture);
            }
        }
        
        public static string EmptyPodcastMessage {
            get {
                return ResourceManager.GetString("EmptyPodcastMessage", resourceCulture);
            }
        }
        
        public static string EpisodesEmptyMessage {
            get {
                return ResourceManager.GetString("EpisodesEmptyMessage", resourceCulture);
            }
        }
        
        public static string DefaultLoadingMessage {
            get {
                return ResourceManager.GetString("DefaultLoadingMessage", resourceCulture);
            }
        }
        
        public static string DefaultSavingMessage {
            get {
                return ResourceManager.GetString("DefaultSavingMessage", resourceCulture);
            }
        }
        
        public static string DefaultEmptyMessage {
            get {
                return ResourceManager.GetString("DefaultEmptyMessage", resourceCulture);
            }
        }
        
        public static string EmptyNotesTitle {
            get {
                return ResourceManager.GetString("EmptyNotesTitle", resourceCulture);
            }
        }
        
        public static string EmptyNotesMessage {
            get {
                return ResourceManager.GetString("EmptyNotesMessage", resourceCulture);
            }
        }
        
        public static string BadgesEmptyMessage {
            get {
                return ResourceManager.GetString("BadgesEmptyMessage", resourceCulture);
            }
        }
        
        public static string NoResultsMessage {
            get {
                return ResourceManager.GetString("NoResultsMessage", resourceCulture);
            }
        }
        
        public static string EmptyCertificatesTitle {
            get {
                return ResourceManager.GetString("EmptyCertificatesTitle", resourceCulture);
            }
        }
        
        public static string EmptyCertificatesMessage {
            get {
                return ResourceManager.GetString("EmptyCertificatesMessage", resourceCulture);
            }
        }
        
        public static string EmptyTagMessage {
            get {
                return ResourceManager.GetString("EmptyTagMessage", resourceCulture);
            }
        }
        
        public static string EmptyUnspecifiedTagMessage {
            get {
                return ResourceManager.GetString("EmptyUnspecifiedTagMessage", resourceCulture);
            }
        }
        
        public static string EmptyFollowingTitle {
            get {
                return ResourceManager.GetString("EmptyFollowingTitle", resourceCulture);
            }
        }
        
        public static string EmptyFollowingMessage {
            get {
                return ResourceManager.GetString("EmptyFollowingMessage", resourceCulture);
            }
        }
        
        public static string EmptyGroupsMessage {
            get {
                return ResourceManager.GetString("EmptyGroupsMessage", resourceCulture);
            }
        }
        
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        public static string DeviceSettingsLabel {
            get {
                return ResourceManager.GetString("DeviceSettingsLabel", resourceCulture);
            }
        }
        
        public static string LogOutLabel {
            get {
                return ResourceManager.GetString("LogOutLabel", resourceCulture);
            }
        }
        
        public static string FirebaseTokenMessage {
            get {
                return ResourceManager.GetString("FirebaseTokenMessage", resourceCulture);
            }
        }
        
        public static string CommentsTitleLabel {
            get {
                return ResourceManager.GetString("CommentsTitleLabel", resourceCulture);
            }
        }
        
        public static string NotificationChannel {
            get {
                return ResourceManager.GetString("NotificationChannel", resourceCulture);
            }
        }
        
        public static string FinishingOnboardingLabel {
            get {
                return ResourceManager.GetString("FinishingOnboardingLabel", resourceCulture);
            }
        }
        
        public static string TabHomeLabel {
            get {
                return ResourceManager.GetString("TabHomeLabel", resourceCulture);
            }
        }
        
        public static string TabMediaLabel {
            get {
                return ResourceManager.GetString("TabMediaLabel", resourceCulture);
            }
        }
        
        public static string TabSearchLabel {
            get {
                return ResourceManager.GetString("TabSearchLabel", resourceCulture);
            }
        }
        
        public static string TabAccountLabel {
            get {
                return ResourceManager.GetString("TabAccountLabel", resourceCulture);
            }
        }
        
        public static string TabRecommendationsLabel {
            get {
                return ResourceManager.GetString("TabRecommendationsLabel", resourceCulture);
            }
        }
        
        public static string TabTrendingLabel {
            get {
                return ResourceManager.GetString("TabTrendingLabel", resourceCulture);
            }
        }
        
        public static string TabNewLabel {
            get {
                return ResourceManager.GetString("TabNewLabel", resourceCulture);
            }
        }
        
        public static string TabCertificatesLabel {
            get {
                return ResourceManager.GetString("TabCertificatesLabel", resourceCulture);
            }
        }
        
        public static string TabMyContentLabel {
            get {
                return ResourceManager.GetString("TabMyContentLabel", resourceCulture);
            }
        }
        
        public static string TabHistoryLabel {
            get {
                return ResourceManager.GetString("TabHistoryLabel", resourceCulture);
            }
        }
        
        public static string TabStatsLabel {
            get {
                return ResourceManager.GetString("TabStatsLabel", resourceCulture);
            }
        }
        
        public static string TabGoalsLabel {
            get {
                return ResourceManager.GetString("TabGoalsLabel", resourceCulture);
            }
        }
        
        public static string TabNotesLabel {
            get {
                return ResourceManager.GetString("TabNotesLabel", resourceCulture);
            }
        }
        
        public static string TabBadgesLabel {
            get {
                return ResourceManager.GetString("TabBadgesLabel", resourceCulture);
            }
        }
        
        public static string TabFollowingLabel {
            get {
                return ResourceManager.GetString("TabFollowingLabel", resourceCulture);
            }
        }
        
        public static string DefaultErrorTitle {
            get {
                return ResourceManager.GetString("DefaultErrorTitle", resourceCulture);
            }
        }
        
        public static string InterestsTitle {
            get {
                return ResourceManager.GetString("InterestsTitle", resourceCulture);
            }
        }
        
        public static string DefaultErrorDismissButton {
            get {
                return ResourceManager.GetString("DefaultErrorDismissButton", resourceCulture);
            }
        }
        
        public static string NoLearnerError {
            get {
                return ResourceManager.GetString("NoLearnerError", resourceCulture);
            }
        }
        
        public static string StatementSendError {
            get {
                return ResourceManager.GetString("StatementSendError", resourceCulture);
            }
        }
        
        public static string OfflineMessageTitle {
            get {
                return ResourceManager.GetString("OfflineMessageTitle", resourceCulture);
            }
        }
        
        public static string JsonErrorMessage {
            get {
                return ResourceManager.GetString("JsonErrorMessage", resourceCulture);
            }
        }
        
        public static string AuthenticationErrorMessage {
            get {
                return ResourceManager.GetString("AuthenticationErrorMessage", resourceCulture);
            }
        }
        
        public static string ServerErrorMessage {
            get {
                return ResourceManager.GetString("ServerErrorMessage", resourceCulture);
            }
        }
        
        public static string UnknownErrorMessage {
            get {
                return ResourceManager.GetString("UnknownErrorMessage", resourceCulture);
            }
        }
        
        public static string ActivityLaunchError {
            get {
                return ResourceManager.GetString("ActivityLaunchError", resourceCulture);
            }
        }
        
        public static string DownloadError {
            get {
                return ResourceManager.GetString("DownloadError", resourceCulture);
            }
        }
        
        public static string ShareError {
            get {
                return ResourceManager.GetString("ShareError", resourceCulture);
            }
        }
        
        public static string TypeCourse {
            get {
                return ResourceManager.GetString("TypeCourse", resourceCulture);
            }
        }
        
        public static string TypeCoursePlural {
            get {
                return ResourceManager.GetString("TypeCoursePlural", resourceCulture);
            }
        }
        
        public static string TypeFlashCard {
            get {
                return ResourceManager.GetString("TypeFlashCard", resourceCulture);
            }
        }
        
        public static string TypeTip {
            get {
                return ResourceManager.GetString("TypeTip", resourceCulture);
            }
        }
        
        public static string TypeQuiz {
            get {
                return ResourceManager.GetString("TypeQuiz", resourceCulture);
            }
        }
        
        public static string TypeTest {
            get {
                return ResourceManager.GetString("TypeTest", resourceCulture);
            }
        }
        
        public static string TypePodcast {
            get {
                return ResourceManager.GetString("TypePodcast", resourceCulture);
            }
        }
        
        public static string TypeEpisode {
            get {
                return ResourceManager.GetString("TypeEpisode", resourceCulture);
            }
        }
        
        public static string TypeArticle {
            get {
                return ResourceManager.GetString("TypeArticle", resourceCulture);
            }
        }
        
        public static string TypeArticlePlural {
            get {
                return ResourceManager.GetString("TypeArticlePlural", resourceCulture);
            }
        }
        
        public static string SearchPrompt {
            get {
                return ResourceManager.GetString("SearchPrompt", resourceCulture);
            }
        }
        
        public static string SearchNoResultsMessage {
            get {
                return ResourceManager.GetString("SearchNoResultsMessage", resourceCulture);
            }
        }
        
        public static string SearchCantFindLabel {
            get {
                return ResourceManager.GetString("SearchCantFindLabel", resourceCulture);
            }
        }
        
        public static string MakeASuggestionButtonLabel {
            get {
                return ResourceManager.GetString("MakeASuggestionButtonLabel", resourceCulture);
            }
        }
        
        public static string MakeASuggestionTitle {
            get {
                return ResourceManager.GetString("MakeASuggestionTitle", resourceCulture);
            }
        }
        
        public static string FilterPrompt {
            get {
                return ResourceManager.GetString("FilterPrompt", resourceCulture);
            }
        }
        
        public static string SendFeedbackMailSubjectLine {
            get {
                return ResourceManager.GetString("SendFeedbackMailSubjectLine", resourceCulture);
            }
        }
        
        public static string ItemSingular {
            get {
                return ResourceManager.GetString("ItemSingular", resourceCulture);
            }
        }
        
        public static string ItemPlural {
            get {
                return ResourceManager.GetString("ItemPlural", resourceCulture);
            }
        }
        
        public static string HrLabel {
            get {
                return ResourceManager.GetString("HrLabel", resourceCulture);
            }
        }
        
        public static string MinLabel {
            get {
                return ResourceManager.GetString("MinLabel", resourceCulture);
            }
        }
        
        public static string SecLabel {
            get {
                return ResourceManager.GetString("SecLabel", resourceCulture);
            }
        }
        
        public static string CoursePlural {
            get {
                return ResourceManager.GetString("CoursePlural", resourceCulture);
            }
        }
        
        public static string StatLabelSeen {
            get {
                return ResourceManager.GetString("StatLabelSeen", resourceCulture);
            }
        }
        
        public static string StatLabelCompleted {
            get {
                return ResourceManager.GetString("StatLabelCompleted", resourceCulture);
            }
        }
        
        public static string StatLabelAverageScore {
            get {
                return ResourceManager.GetString("StatLabelAverageScore", resourceCulture);
            }
        }
        
        public static string SetAReminderButtonTitle {
            get {
                return ResourceManager.GetString("SetAReminderButtonTitle", resourceCulture);
            }
        }
        
        public static string GoalDetailsButtonTitle {
            get {
                return ResourceManager.GetString("GoalDetailsButtonTitle", resourceCulture);
            }
        }
        
        public static string CustomGoalsButtonTitle {
            get {
                return ResourceManager.GetString("CustomGoalsButtonTitle", resourceCulture);
            }
        }
        
        public static string GoalDetailsTitle {
            get {
                return ResourceManager.GetString("GoalDetailsTitle", resourceCulture);
            }
        }
        
        public static string GoalsHeadingLabel {
            get {
                return ResourceManager.GetString("GoalsHeadingLabel", resourceCulture);
            }
        }
        
        public static string CustomGoalsOverviewLabel {
            get {
                return ResourceManager.GetString("CustomGoalsOverviewLabel", resourceCulture);
            }
        }
        
        public static string YourActivityOverviewLabel {
            get {
                return ResourceManager.GetString("YourActivityOverviewLabel", resourceCulture);
            }
        }
        
        public static string GoalTitleWeeklyArticles {
            get {
                return ResourceManager.GetString("GoalTitleWeeklyArticles", resourceCulture);
            }
        }
        
        public static string GoalTitleCompletedArticles {
            get {
                return ResourceManager.GetString("GoalTitleCompletedArticles", resourceCulture);
            }
        }
        
        public static string GoalTitleTestScore {
            get {
                return ResourceManager.GetString("GoalTitleTestScore", resourceCulture);
            }
        }
        
        public static string GoalTitleMonthlyCourses {
            get {
                return ResourceManager.GetString("GoalTitleMonthlyCourses", resourceCulture);
            }
        }
        
        public static string ModifyGoalButtonLabel {
            get {
                return ResourceManager.GetString("ModifyGoalButtonLabel", resourceCulture);
            }
        }
        
        public static string GoalSatisfiedStatusLabel {
            get {
                return ResourceManager.GetString("GoalSatisfiedStatusLabel", resourceCulture);
            }
        }
        
        public static string GoalTotalLabel {
            get {
                return ResourceManager.GetString("GoalTotalLabel", resourceCulture);
            }
        }
        
        public static string HowManyArticlesViewPerWeekLabel {
            get {
                return ResourceManager.GetString("HowManyArticlesViewPerWeekLabel", resourceCulture);
            }
        }
        
        public static string HowManyArticlesCompletePerWeekLabel {
            get {
                return ResourceManager.GetString("HowManyArticlesCompletePerWeekLabel", resourceCulture);
            }
        }
        
        public static string HowManyCoursesCompletedPerMonthLabel {
            get {
                return ResourceManager.GetString("HowManyCoursesCompletedPerMonthLabel", resourceCulture);
            }
        }
        
        public static string TargetTestScoreQuestionLabel {
            get {
                return ResourceManager.GetString("TargetTestScoreQuestionLabel", resourceCulture);
            }
        }
        
        public static string EarnedMessage {
            get {
                return ResourceManager.GetString("EarnedMessage", resourceCulture);
            }
        }
        
        public static string StartCourseLabel {
            get {
                return ResourceManager.GetString("StartCourseLabel", resourceCulture);
            }
        }
        
        public static string CourseDescriptionLabel {
            get {
                return ResourceManager.GetString("CourseDescriptionLabel", resourceCulture);
            }
        }
        
        public static string HistoryEmptyMessage {
            get {
                return ResourceManager.GetString("HistoryEmptyMessage", resourceCulture);
            }
        }
        
        public static string OfflineMessageBody {
            get {
                return ResourceManager.GetString("OfflineMessageBody", resourceCulture);
            }
        }
        
        public static string SetServerLabel {
            get {
                return ResourceManager.GetString("SetServerLabel", resourceCulture);
            }
        }
        
        public static string ViewAccountLabel {
            get {
                return ResourceManager.GetString("ViewAccountLabel", resourceCulture);
            }
        }
        
        public static string SendFeedbackLabel {
            get {
                return ResourceManager.GetString("SendFeedbackLabel", resourceCulture);
            }
        }
        
        public static string ViewSupportLabel {
            get {
                return ResourceManager.GetString("ViewSupportLabel", resourceCulture);
            }
        }
        
        public static string ViewAcknowledgementsLabel {
            get {
                return ResourceManager.GetString("ViewAcknowledgementsLabel", resourceCulture);
            }
        }
        
        public static string SaveLabel {
            get {
                return ResourceManager.GetString("SaveLabel", resourceCulture);
            }
        }
        
        public static string CertificateLabel {
            get {
                return ResourceManager.GetString("CertificateLabel", resourceCulture);
            }
        }
        
        public static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        public static string SignInLabel {
            get {
                return ResourceManager.GetString("SignInLabel", resourceCulture);
            }
        }
        
        public static string PageLoadingFailedMessage {
            get {
                return ResourceManager.GetString("PageLoadingFailedMessage", resourceCulture);
            }
        }
        
        public static string CorrectLabel {
            get {
                return ResourceManager.GetString("CorrectLabel", resourceCulture);
            }
        }
        
        public static string IncorrectLabel {
            get {
                return ResourceManager.GetString("IncorrectLabel", resourceCulture);
            }
        }
        
        public static string TryAgainLabel {
            get {
                return ResourceManager.GetString("TryAgainLabel", resourceCulture);
            }
        }
        
        public static string TryAgainTitleCaseLabel {
            get {
                return ResourceManager.GetString("TryAgainTitleCaseLabel", resourceCulture);
            }
        }
        
        public static string QLabel {
            get {
                return ResourceManager.GetString("QLabel", resourceCulture);
            }
        }
        
        public static string SessionExpiredErrorMessage {
            get {
                return ResourceManager.GetString("SessionExpiredErrorMessage", resourceCulture);
            }
        }
        
        public static string RecommendationPopupTitle {
            get {
                return ResourceManager.GetString("RecommendationPopupTitle", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string CancelDownload {
            get {
                return ResourceManager.GetString("CancelDownload", resourceCulture);
            }
        }
        
        public static string WelcomeLabel {
            get {
                return ResourceManager.GetString("WelcomeLabel", resourceCulture);
            }
        }
        
        public static string ContinueLabel {
            get {
                return ResourceManager.GetString("ContinueLabel", resourceCulture);
            }
        }
        
        public static string TeamPlaceholderText {
            get {
                return ResourceManager.GetString("TeamPlaceholderText", resourceCulture);
            }
        }
        
        public static string ClearCacheLabel {
            get {
                return ResourceManager.GetString("ClearCacheLabel", resourceCulture);
            }
        }
        
        public static string Okay {
            get {
                return ResourceManager.GetString("Okay", resourceCulture);
            }
        }
        
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        public static string LocalLoginLabel {
            get {
                return ResourceManager.GetString("LocalLoginLabel", resourceCulture);
            }
        }
        
        public static string EnableLocalLoginMessage {
            get {
                return ResourceManager.GetString("EnableLocalLoginMessage", resourceCulture);
            }
        }
        
        public static string DisableLocalLoginMessage {
            get {
                return ResourceManager.GetString("DisableLocalLoginMessage", resourceCulture);
            }
        }
        
        public static string ConfirmClearCache {
            get {
                return ResourceManager.GetString("ConfirmClearCache", resourceCulture);
            }
        }
        
        public static string NextQuestionLabel {
            get {
                return ResourceManager.GetString("NextQuestionLabel", resourceCulture);
            }
        }
        
        public static string PreviousQuestionLabel {
            get {
                return ResourceManager.GetString("PreviousQuestionLabel", resourceCulture);
            }
        }
        
        public static string CorrectAnswersLabel {
            get {
                return ResourceManager.GetString("CorrectAnswersLabel", resourceCulture);
            }
        }
        
        public static string TestResultsMessage {
            get {
                return ResourceManager.GetString("TestResultsMessage", resourceCulture);
            }
        }
        
        public static string DownloadManagement {
            get {
                return ResourceManager.GetString("DownloadManagement", resourceCulture);
            }
        }
        
        public static string DeleteDownloadsLabel {
            get {
                return ResourceManager.GetString("DeleteDownloadsLabel", resourceCulture);
            }
        }
        
        public static string DownloadSizeLabel {
            get {
                return ResourceManager.GetString("DownloadSizeLabel", resourceCulture);
            }
        }
        
        public static string YourDownloads {
            get {
                return ResourceManager.GetString("YourDownloads", resourceCulture);
            }
        }
        
        public static string LessThanOne {
            get {
                return ResourceManager.GetString("LessThanOne", resourceCulture);
            }
        }
        
        public static string DeleteAnnotationTitle {
            get {
                return ResourceManager.GetString("DeleteAnnotationTitle", resourceCulture);
            }
        }
        
        public static string DeleteAnnotationMessage {
            get {
                return ResourceManager.GetString("DeleteAnnotationMessage", resourceCulture);
            }
        }
        
        public static string DeleteDownloadsTitle {
            get {
                return ResourceManager.GetString("DeleteDownloadsTitle", resourceCulture);
            }
        }
        
        public static string DeleteDownloadsMessage {
            get {
                return ResourceManager.GetString("DeleteDownloadsMessage", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string Lessons {
            get {
                return ResourceManager.GetString("Lessons", resourceCulture);
            }
        }
        
        public static string Lesson {
            get {
                return ResourceManager.GetString("Lesson", resourceCulture);
            }
        }
        
        public static string Episodes {
            get {
                return ResourceManager.GetString("Episodes", resourceCulture);
            }
        }
        
        public static string Episode {
            get {
                return ResourceManager.GetString("Episode", resourceCulture);
            }
        }
        
        public static string CompleteLabel {
            get {
                return ResourceManager.GetString("CompleteLabel", resourceCulture);
            }
        }
        
        public static string DefaultContentName {
            get {
                return ResourceManager.GetString("DefaultContentName", resourceCulture);
            }
        }
        
        public static string DownloadWithProgress {
            get {
                return ResourceManager.GetString("DownloadWithProgress", resourceCulture);
            }
        }
        
        public static string DownloadNoProgress {
            get {
                return ResourceManager.GetString("DownloadNoProgress", resourceCulture);
            }
        }
        
        public static string PromptResultsTitle {
            get {
                return ResourceManager.GetString("PromptResultsTitle", resourceCulture);
            }
        }
        
        public static string PromptResultsMessage {
            get {
                return ResourceManager.GetString("PromptResultsMessage", resourceCulture);
            }
        }
        
        public static string EmptyViewErrorTitle {
            get {
                return ResourceManager.GetString("EmptyViewErrorTitle", resourceCulture);
            }
        }
        
        public static string UnsupportedContentTitle {
            get {
                return ResourceManager.GetString("UnsupportedContentTitle", resourceCulture);
            }
        }
        
        public static string UnsupportedContentMessage {
            get {
                return ResourceManager.GetString("UnsupportedContentMessage", resourceCulture);
            }
        }
        
        public static string ViewPodcastLabel {
            get {
                return ResourceManager.GetString("ViewPodcastLabel", resourceCulture);
            }
        }
        
        public static string PodcastsLabel {
            get {
                return ResourceManager.GetString("PodcastsLabel", resourceCulture);
            }
        }
        
        public static string EpisodeTrackInformation {
            get {
                return ResourceManager.GetString("EpisodeTrackInformation", resourceCulture);
            }
        }
        
        public static string SubscribeButtonTitle {
            get {
                return ResourceManager.GetString("SubscribeButtonTitle", resourceCulture);
            }
        }
        
        public static string UnsubscribeButtonTitle {
            get {
                return ResourceManager.GetString("UnsubscribeButtonTitle", resourceCulture);
            }
        }
        
        public static string PlayedLabel {
            get {
                return ResourceManager.GetString("PlayedLabel", resourceCulture);
            }
        }
        
        public static string TermsOfUseText {
            get {
                return ResourceManager.GetString("TermsOfUseText", resourceCulture);
            }
        }
        
        public static string RemindersDisabledTitle {
            get {
                return ResourceManager.GetString("RemindersDisabledTitle", resourceCulture);
            }
        }
        
        public static string RemindersDisabledMessage {
            get {
                return ResourceManager.GetString("RemindersDisabledMessage", resourceCulture);
            }
        }
        
        public static string RemindersErrorTitle {
            get {
                return ResourceManager.GetString("RemindersErrorTitle", resourceCulture);
            }
        }
        
        public static string RemindersErrorMessage {
            get {
                return ResourceManager.GetString("RemindersErrorMessage", resourceCulture);
            }
        }
        
        public static string ReminderTitle {
            get {
                return ResourceManager.GetString("ReminderTitle", resourceCulture);
            }
        }
        
        public static string ReminderChooseDays {
            get {
                return ResourceManager.GetString("ReminderChooseDays", resourceCulture);
            }
        }
        
        public static string ReminderChooseTime {
            get {
                return ResourceManager.GetString("ReminderChooseTime", resourceCulture);
            }
        }
        
        public static string ReminderBody {
            get {
                return ResourceManager.GetString("ReminderBody", resourceCulture);
            }
        }
        
        public static string EnterURLMessage {
            get {
                return ResourceManager.GetString("EnterURLMessage", resourceCulture);
            }
        }
        
        public static string FileNotFoundTitle {
            get {
                return ResourceManager.GetString("FileNotFoundTitle", resourceCulture);
            }
        }
        
        public static string FileNotFoundMessage {
            get {
                return ResourceManager.GetString("FileNotFoundMessage", resourceCulture);
            }
        }
        
        public static string FollowButtonLabel {
            get {
                return ResourceManager.GetString("FollowButtonLabel", resourceCulture);
            }
        }
        
        public static string UnfollowButtonLabel {
            get {
                return ResourceManager.GetString("UnfollowButtonLabel", resourceCulture);
            }
        }
        
        public static string FollowErrorMessage {
            get {
                return ResourceManager.GetString("FollowErrorMessage", resourceCulture);
            }
        }
        
        public static string ViewTermErrorMessage {
            get {
                return ResourceManager.GetString("ViewTermErrorMessage", resourceCulture);
            }
        }
        
        public static string ItemNotFoundMessage {
            get {
                return ResourceManager.GetString("ItemNotFoundMessage", resourceCulture);
            }
        }
        
        public static string GroupTopicsEmptyTitle {
            get {
                return ResourceManager.GetString("GroupTopicsEmptyTitle", resourceCulture);
            }
        }
        
        public static string ViewMoreButtonLabel {
            get {
                return ResourceManager.GetString("ViewMoreButtonLabel", resourceCulture);
            }
        }
        
        public static string LeaveGroupButtonLabel {
            get {
                return ResourceManager.GetString("LeaveGroupButtonLabel", resourceCulture);
            }
        }
        
        public static string EmptyCourseTitleLabel {
            get {
                return ResourceManager.GetString("EmptyCourseTitleLabel", resourceCulture);
            }
        }
        
        public static string EmptyCourseMessageLabel {
            get {
                return ResourceManager.GetString("EmptyCourseMessageLabel", resourceCulture);
            }
        }
        
        public static string EmptyGroupTopicTitle {
            get {
                return ResourceManager.GetString("EmptyGroupTopicTitle", resourceCulture);
            }
        }
        
        public static string EmptyGroupTopicMessage {
            get {
                return ResourceManager.GetString("EmptyGroupTopicMessage", resourceCulture);
            }
        }
        
        public static string EmptyEnhancedDashboardTitle {
            get {
                return ResourceManager.GetString("EmptyEnhancedDashboardTitle", resourceCulture);
            }
        }
    }
}
