//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PERLS.Data {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsSpecific {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsSpecific() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PERLS.Data.StringsSpecific", typeof(StringsSpecific).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string TermsOfUseText {
            get {
                return ResourceManager.GetString("TermsOfUseText", resourceCulture);
            }
        }
        
        public static string ViewTermsLabel {
            get {
                return ResourceManager.GetString("ViewTermsLabel", resourceCulture);
            }
        }
        
        public static string TabGroupsLabel {
            get {
                return ResourceManager.GetString("TabGroupsLabel", resourceCulture);
            }
        }
        
        public static string GroupsTitle {
            get {
                return ResourceManager.GetString("GroupsTitle", resourceCulture);
            }
        }
        
        public static string EmptyGroupsTitle {
            get {
                return ResourceManager.GetString("EmptyGroupsTitle", resourceCulture);
            }
        }
        
        public static string EmptyGroupMessage {
            get {
                return ResourceManager.GetString("EmptyGroupMessage", resourceCulture);
            }
        }
        
        public static string MoreGroupsSubtitle {
            get {
                return ResourceManager.GetString("MoreGroupsSubtitle", resourceCulture);
            }
        }
        
        public static string JoinedGroupsTitle {
            get {
                return ResourceManager.GetString("JoinedGroupsTitle", resourceCulture);
            }
        }
        
        public static string JoinableGroupsTitle {
            get {
                return ResourceManager.GetString("JoinableGroupsTitle", resourceCulture);
            }
        }
        
        public static string GroupTopicsEmptyMessage {
            get {
                return ResourceManager.GetString("GroupTopicsEmptyMessage", resourceCulture);
            }
        }
        
        public static string GroupsErrorMessage {
            get {
                return ResourceManager.GetString("GroupsErrorMessage", resourceCulture);
            }
        }
        
        public static string BookmarksEmptyMessage {
            get {
                return ResourceManager.GetString("BookmarksEmptyMessage", resourceCulture);
            }
        }
        
        public static string TabBookmarksLabel {
            get {
                return ResourceManager.GetString("TabBookmarksLabel", resourceCulture);
            }
        }
        
        public static string BookmarkErrorMessage {
            get {
                return ResourceManager.GetString("BookmarkErrorMessage", resourceCulture);
            }
        }
        
        public static string StatLabelBookmarked {
            get {
                return ResourceManager.GetString("StatLabelBookmarked", resourceCulture);
            }
        }
        
        public static string OnboardingPageOneTitleLabel {
            get {
                return ResourceManager.GetString("OnboardingPageOneTitleLabel", resourceCulture);
            }
        }
        
        public static string OnboardingPageTwoTitleLabel {
            get {
                return ResourceManager.GetString("OnboardingPageTwoTitleLabel", resourceCulture);
            }
        }
        
        public static string OnboardingPageThreeTitleLabel {
            get {
                return ResourceManager.GetString("OnboardingPageThreeTitleLabel", resourceCulture);
            }
        }
        
        public static string OnboardingPageOneDescriptionLabel {
            get {
                return ResourceManager.GetString("OnboardingPageOneDescriptionLabel", resourceCulture);
            }
        }
        
        public static string OnboardingPageTwoDescriptionLabel {
            get {
                return ResourceManager.GetString("OnboardingPageTwoDescriptionLabel", resourceCulture);
            }
        }
        
        public static string OnboardingPageThreeDescriptionLabel {
            get {
                return ResourceManager.GetString("OnboardingPageThreeDescriptionLabel", resourceCulture);
            }
        }
    }
}
